bind_addr = "0.0.0.0:4000"

[database]
url = "postgres://controlplane:controlplane_password@localhost:5433/controlplane"

[kafka]
bootstrap_servers = "127.0.0.1:19092"

[unity_catalog]
base_url = "http://localhost:8082/api/2.1/unity-catalog"

[keycloak]
url = "http://keycloak-svc.keycloak.svc.cluster.local:8080"
realm = "sovico"
audiences = []
