bind_addr = "0.0.0.0:4000"
bypass_token = "test"

[telemetry]
enabled = false

[chronicle]
enabled = true
base_url = "http://localhost:3008"
source = "controlplane"

[database]
url = "postgres://controlplane:controlplane_password@localhost:5433/controlplane"

[dagster]
base_url = "http://localhost:8088"

[kafka]
bootstrap_servers = "127.0.0.1:19092"

[unity_catalog]
base_url = "http://localhost:8082/api/2.1/unity-catalog"
admin_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiIsImtpZCI6IjA5MWJlZjFhMjc0ODY0MDc1MTkwYjZkMjFkNjI0YTEzOWQ0NmFjMTAifQ.eyJzdWIiOiJhZG1pbiIsImlzcyI6ImludGVybmFsIiwiaWF0IjoxNzg3NTQ5Nzc2LCJqdGkiOiI4MzY1OTYxMy0zZDNlLTQ1YzUtYjA2NC1iOWRmZDdlZDc5NzgiLCJ0eXBlIjoiU0VSVklDRSJ9.A1DYRLnpB9ul9qCi2xnEoeSxdP2jFvE7ajpcXJsy-4gZP99MBmGpy9-YvQrLycAtM0eUKh717wN3zdx0KD_M9DKyv6ny1oz3VL0qIA_y2PNXmQQ5dDy0JnfGpmPPYtaV2L_iW4f7kEXqT6Kk8YHyqgmk_5J6_X6Vjh-nXOBh57FlInWuabMiQt5R0HifbpBzgQ9ZwLzXfFpYLV9ZaUmJgsSPyew89xc2a3JrHo6FnOwncaX3sKKzQfy6jS3cSghOzmmCYx-2wvh_h6_vr8G7hhVUgrj6CgcJjLqzPEzcfj4cZB_Acnnrk0EdrSx5FbnjdFXONSqII0eWUS_kTdKL2Q"
#admin_token_file = "../uc/config/token.txt"

[keycloak]
# url = "http://keycloak-svc.keycloak.svc.cluster.local:8080"
url = "http://localhost:8080"
realm = "sovico"
issuers = [
  "http://keycloak-svc.keycloak.svc.cluster.local:8080/realms/sovico",
  "http://127.0.0.1:8083/realms/sovico",
  "http://localhost:8083/realms/sovico",
]
audiences = []

[duckdb_server]
uri = "quack:localhost:8090"

[openai]
api_key = ""
model = "gpt-5.4-nano"
base_url = "https://api.openai.com/v1"
