apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: unitycatalog
type: Opaque
stringData:
  POSTGRES_DB: ucdb
  POSTGRES_USER: ucuser
  POSTGRES_PASSWORD: ucpassword
  DATABASE_URL: "postgres://ucuser:ucpassword@dagster-postgresql.dagster.svc.cluster.local:5432/ucdb"
