apiVersion: v1
kind: ConfigMap
metadata:
  name: unitycatalog-config
  namespace: unitycatalog
data:
  server.toml: |
    [server]
    env = "dev"
    host = "0.0.0.0"
    port = 8080
    public_url = "http://localhost:8082"
    authorization = "enable"
    authorization_url = "http://keycloak-svc.keycloak.svc.cluster.local:8080/realms/sovico/protocol/openid-connect/auth"
    token_url = "http://keycloak-svc.keycloak.svc.cluster.local:8080/realms/sovico/protocol/openid-connect/token"
    client_id = "webui"
    client_secret = "webui-secret"
    redirect_port = 8082
    allowed_issuers = ["http://keycloak-svc.keycloak.svc.cluster.local:8080/realms/sovico"]
    audiences = ["webui"]
    cookie_timeout = "P5D"

    [server.managed_table]
    enabled = true

    [database]
    url = "postgres://ucuser:ucpassword@unitycatalog-postgres-svc:5432/ucdb"
    max_connections = 20

    [[s3]]
    bucket_path = "s3://unitycatalog/"
    region = "us-east-1"
    access_key = "rustfsadmin"
    secret_key = "rustfsadmin"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unitycatalog
  namespace: unitycatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unitycatalog
  template:
    metadata:
      labels:
        app: unitycatalog
    spec:
      containers:
        - name: unitycatalog
          image: mizumi-uc:0.1.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 8080
              name: rest
          volumeMounts:
            - name: config
              mountPath: /app/config/server.toml
              subPath: server.toml
      volumes:
        - name: config
          configMap:
            name: unitycatalog-config
---
apiVersion: v1
kind: Service
metadata:
  name: unitycatalog-svc
  namespace: unitycatalog
spec:
  selector:
    app: unitycatalog
  ports:
    - name: rest
      port: 8080
      targetPort: 8080
