apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unitycatalog-h2-pvc
  namespace: unitycatalog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unitycatalog-config
  namespace: unitycatalog
data:
  hibernate.properties: |
    hibernate.connection.driver_class=org.h2.Driver
    hibernate.connection.url=jdbc:h2:file:/data/db/h2db;DB_CLOSE_DELAY=-1
    hibernate.hbm2ddl.auto=update
    hibernate.show_sql=false
    hibernate.archive.autodetection=class
    hibernate.use_sql_comments=true
    org.hibernate.SQL=INFO
    org.hibernate.type.descriptor.sql.BasicBinder=TRACE
  server.properties: |
    server.env=dev
    server.authorization=enable
    server.authorization-url=http://keycloak-svc.keycloak.svc.cluster.local:8080/realms/sovico/protocol/openid-connect/auth
    server.token-url=http://keycloak-svc.keycloak.svc.cluster.local:8080/realms/sovico/protocol/openid-connect/token
    server.client-id=app-ui
    server.client-secret=app-ui-secret
    server.redirect-port=
    server.allowed-issuers=http://keycloak-svc.keycloak.svc.cluster.local:8080/realms/sovico
    server.audiences=app-ui
    server.cookie-timeout=P5D
    server.managed-table.enabled=true
    s3.bucketPath.0=s3://unitycatalog/
    s3.region.0=us-east-1
    s3.accessKey.0=rustfsadmin
    s3.secretKey.0=rustfsadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unitycatalog
  namespace: unitycatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unitycatalog
  template:
    metadata:
      labels:
        app: unitycatalog
    spec:
      containers:
        - name: unitycatalog
          image: mizumi-unitycatalog:v0.4.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 8080
              name: rest
            - containerPort: 8081
              name: grpc
          volumeMounts:
            - name: config
              mountPath: /home/unitycatalog/etc/conf/hibernate.properties
              subPath: hibernate.properties
            - name: config
              mountPath: /home/unitycatalog/etc/conf/server.properties
              subPath: server.properties
            - name: h2-data
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: unitycatalog-config
        - name: h2-data
          persistentVolumeClaim:
            claimName: unitycatalog-h2-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: unitycatalog-svc
  namespace: unitycatalog
spec:
  selector:
    app: unitycatalog
  ports:
    - name: rest
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 8081
      targetPort: 8081
