apiVersion: apps/v1
kind: Deployment
metadata:
  name: unitycatalog-ui
  namespace: unitycatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unitycatalog-ui
  template:
    metadata:
      labels:
        app: unitycatalog-ui
    spec:
      containers:
        - name: unitycatalog-ui
          image: mizumi-unitycatalog-ui:v0.4.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 200m
              memory: 2Gi
          ports:
            - containerPort: 3000
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: BROWSER
              value: "none"
---
apiVersion: v1
kind: Service
metadata:
  name: unitycatalog-ui-svc
  namespace: unitycatalog
spec:
  selector:
    app: unitycatalog-ui
  ports:
    - port: 3000
      targetPort: 3000
