dagster-user-deployments:
  deployments:
    - name: mizumi
      image:
        repository: mizumi-dagster
        tag: "1.13.4"
        pullPolicy: IfNotPresent
      dagsterApiGrpcArgs:
        - "--python-file"
        - "/app/definitions.py"
      port: 3030
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: 2000m
          memory: 4Gi

dagsterWebserver:
  replicaCount: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

dagsterDaemon:
  enabled: true
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: 2000m
          memory: 4Gi
