global:
  postgresqlSecretName: dagster-postgresql-secret

dagster-user-deployments:
  deployments:
    - name: mizumi
      image:
        repository: mizumi-dagster
        tag: "1.13.4"
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "--python-file"
        - "/app/definitions.py"
      port: 3030
      resources:
        requests:
          cpu: 75m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 768Mi

dagsterWebserver:
  replicaCount: 1
  resources:
    requests:
      cpu: 75m
      memory: 384Mi
    limits:
      cpu: 250m
      memory: 768Mi

dagsterDaemon:
  enabled: true
  resources:
    requests:
      cpu: 250m
      memory: 384Mi
    limits:
      cpu: "1"
      memory: 768Mi

runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      resources:
        requests:
          cpu: 125m
          memory: 512Mi
        limits:
          cpu: 250m
          memory: 1Gi

postgresql:
  enabled: false
  postgresqlHost: dagster-postgresql
  postgresqlUsername: dagster
  postgresqlPassword: dagster_password
  postgresqlDatabase: dagster
