spark.sql.warehouse.dir                     s3a://gold/sdp-warehouse
spark.sql.extensions                        io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.mizumi                    io.unitycatalog.spark.UCSingleCatalog
spark.sql.catalog.mizumi.uri                http://unitycatalog-svc.unitycatalog.svc.cluster.local:8080
spark.sql.catalog.mizumi.token
