spark.sql.warehouse.dir                     s3a://gold/banking/sdp-warehouse

spark.sql.catalog.mizumi                    io.unitycatalog.spark.UCSingleCatalog
spark.sql.catalog.mizumi.uri                http://unitycatalog-svc.unitycatalog.svc.cluster.local:8080
spark.sql.catalog.mizumi.token
spark.hadoop.fs.s3.impl                     org.apache.hadoop.fs.s3a.S3AFileSystem
