LOAD unity_catalog;
CREATE SECRET (
     TYPE unity_catalog,
     TOKEN 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJCTTNIdFJmRGhBQVQ4cDhOdHRNVmN2Ym5xNUNtNnB2RUp4Q1hZVUhXYW1nIn0.eyJleHAiOjE3Nzg4MDQ1OTcsImlhdCI6MTc3ODgwNDI5NywiYXV0aF90aW1lIjoxNzc4ODAzMjY0LCJqdGkiOiIxMTgzOGIzYS1jODhlLTRhZWUtNWQ4YS03OGE1MDJmMTMxZWQiLCJpc3MiOiJodHRwOi8va2V5Y2xvYWstc3ZjLmtleWNsb2FrLnN2Yy5jbHVzdGVyLmxvY2FsOjgwODAvcmVhbG1zL3NvdmljbyIsImF1ZCI6IndlYnVpIiwic3ViIjoiYjNjZDQyOTQtZjYwNS00NTlkLTg5N2MtNmM1NWY2MGU4MjIyIiwidHlwIjoiSUQiLCJhenAiOiJ3ZWJ1aSIsInNpZCI6IjI2NzE1NGIzLTg1YWEtNDBlNy1iMzE3LWE5ZmNmNGMxNDc0OSIsImF0X2hhc2giOiJxZ0RCSERXSjJrUzV3cmlGejc5MlVBIiwiYWNyIjoiMCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiTGluaCBUcmFuIiwicHJlZmVycmVkX3VzZXJuYW1lIjoibGluaEBnbWFpbC5jb20iLCJnaXZlbl9uYW1lIjoiTGluaCIsImZhbWlseV9uYW1lIjoiVHJhbiIsImVtYWlsIjoibGluaEBnbWFpbC5jb20ifQ.BXABFW44bn9fTIJRVNdRzeqGhRGDEyaXbi6m_V3Sc1Zr-nxYEJJY1hhD9bF0i3eaD9_gHcRP_kLTmFb_pUtGQMra_LX_Ei2fq7Kl2upHTRW-Tziraz9vfiF0ArOZiIQnSUC0SobPaT1bitJfI0pvihJ5w35wwPk1Fck9BoyCZh7kJLzF4dCyIuPww8s_m9Zzm-2q9_4aTdSPqrVM9xumQQFfeMQhVRn7ue2rKCPPCkXRPHLi3LgYE8HidZVaURheKZnWL9bPCjwvBh3bU2PUsWMl1giXQio91Liwo1TxvVcT_mowY-Dd3B63dceQ34jnSoVFJKczdXgB3tQ-g2akQQ',
     ENDPOINT 'http://localhost:8082'
);
ATTACH 'hdbank' AS hdbank (
     TYPE unity_catalog,
     DEFAULT_SCHEMA 'hdbank_payments_prod_bronze'
);
ATTACH 'vietjetair' AS vietjetair (
     TYPE unity_catalog,
     DEFAULT_SCHEMA 'vietjetair_bookings_prod_bronze'
);
SHOW ALL TABLES;