LOAD unity_catalog;
CREATE SECRET (
     TYPE unity_catalog,
     TOKEN 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJCTTNIdFJmRGhBQVQ4cDhOdHRNVmN2Ym5xNUNtNnB2RUp4Q1hZVUhXYW1nIn0.eyJleHAiOjE3Nzg3NzEyNTgsImlhdCI6MTc3ODc3MDk1OCwiYXV0aF90aW1lIjoxNzc4NzcwMTk5LCJqdGkiOiJjZmFhN2QxZC1lZWU1LWViNzUtMTI4My1iMjgzY2Y2NzFhNGQiLCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwODMvcmVhbG1zL3NvdmljbyIsImF1ZCI6IndlYnVpIiwic3ViIjoiYjNjZDQyOTQtZjYwNS00NTlkLTg5N2MtNmM1NWY2MGU4MjIyIiwidHlwIjoiSUQiLCJhenAiOiJ3ZWJ1aSIsInNpZCI6Ijc2ZGRhMjNlLTVkOTQtNDc5Ny1hODkxLWE5ZmJlYzE1MmMyNiIsImF0X2hhc2giOiJLSU8yYVNWNnJUdkk1Y1YtZXZrZ2NnIiwiYWNyIjoiMCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiTGluaCBUcmFuIiwicHJlZmVycmVkX3VzZXJuYW1lIjoibGluaEBnbWFpbC5jb20iLCJnaXZlbl9uYW1lIjoiTGluaCIsImZhbWlseV9uYW1lIjoiVHJhbiIsImVtYWlsIjoibGluaEBnbWFpbC5jb20ifQ.HHJTCGH7a8phAQxsVDjXk7p3FQExtORKQCzRjtpLWydpyZRapiqg0nhv9Xuhx-3TuQskiFLYeZCZGK8r46XWMvlYqO9lq8ssYvbr0jEkVPiBo2h3UawR5FeJLIQbTLpV3PSfdzfJSr-JaJz50k1v-QmtJdaPCv9G-GvCyC_Ezj5WesKRg3wSaonQ1KlYHtekUJRIsr19AHw5lZtdYH06eyKFC85DpioVccTr-44Q_VoiEUIgSsCUjp_17L1P_9_Qbx8ENRV1e5OE5KGz7Ip98kGI6RIg2PZLLg4cqQSAHWsMrjDxH-7BPOcgkjUYDYpiKvborZhbhML_yXgxDr8UbA',
     ENDPOINT 'http://localhost:8082'
);
ATTACH 'hdbank' AS hdbank (
     TYPE unity_catalog,
     DEFAULT_SCHEMA 'hdbank_payments_prod_bronze'
);
ATTACH 'vietjetair' AS vietjetair (
     TYPE unity_catalog,
     DEFAULT_SCHEMA 'vietjetair_bookings_prod_bronze'
);
SHOW ALL TABLES;
ATTACH 'unity' AS unity (TYPE unity_catalog, DEFAULT_SCHEMA 'default');