export const OTA_TRAVEL_MERCHANTS = [
	"Trip.com",
	"Traveloka",
	"Booking.com",
	"Agoda",
]

export const AIRLINE_TRAVEL_MERCHANTS = [
	"Vietnam Airlines",
	"Vietjet Air",
	"Bamboo Airways",
	"Pacific Airlines",
	"Vasco",
	"Air China",
	"China Southern Airlines",
	"China Eastern Airlines",
	"Hainan Airlines",
	"Shenzhen Airlines",
	"Sichuan Airlines",
	"Spring Airlines",
	"Japan Airlines",
	"All Nippon Airways",
	"Peach Aviation",
	"Jetstar Japan",
	"Skymark Airlines",
	"Korean Air",
	"Asiana Airlines",
	"Jeju Air",
	"Jin Air",
	"T'way Air",
	"Air Premia",
	"United Airlines",
	"Delta Air Lines",
	"American Airlines",
	"Alaska Airlines",
	"Hawaiian Airlines",
	"JetBlue Airways",
	"Singapore Airlines",
	"Scoot",
] as const

export const FAMOUS_PLACE_TRAVEL_MERCHANTS = [
	"Sun World Ba Na Hills",
	"VinWonders Nha Trang",
	"Fansipan Legend",
	"Ha Long Bay Cruise",
	"Hoi An Ancient Town Pass",
	"Phong Nha Cave Tour",
	"Universal Studios Singapore",
	"Marina Bay Sands",
	"Gardens by the Bay",
	"Sentosa Attractions",
	"Tokyo Disneyland",
	"Tokyo DisneySea",
	"Mount Fuji Excursion",
	"Osaka Universal Studios Japan",
	"Kyoto Heritage Tour",
	"Lotte World Seoul",
	"Everland Resort",
	"N Seoul Tower",
	"Jeju Island Resort",
	"Shanghai Disneyland",
	"The Bund River Cruise",
	"Beijing Universal Resort",
	"West Lake Hangzhou Tour",
	"Guilin Li River Cruise",
	"Statue of Liberty Ferry",
	"Grand Canyon Tour",
	"Las Vegas Strip Resort",
	"Yosemite Lodge",
	"Waikiki Beach Resort",
]
