apiVersion: batch/v1
kind: Job
metadata:
  name: rustfs-medallion-pipeline-submit
  namespace: spark
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: spark-operator-spark
      restartPolicy: Never
      containers:
        - name: submit
          image: mizumi-spark-rustfs:4.1.1
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -ec
            - |
              spark-pipelines \
                --jars /opt/spark/jars/hadoop-aws-3.4.2.jar,/opt/spark/jars/aws-java-sdk-bundle-1.12.720.jar,/opt/spark/jars/bundle-2.29.52.jar,/opt/spark/jars/analyticsaccelerator-s3-1.2.1.jar,/opt/spark/jars/wildfly-openssl-2.1.4.Final.jar \
                run \
                --spec /opt/spark/pipelines/spark-pipeline.yaml
