apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
  namespace: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      containers:
        - name: console
          image: docker.redpanda.com/redpandadata/console:v2.8.3
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BROKERS
              value: "redpanda-svc.redpanda.svc.cluster.local:9092"
            - name: REDPANDA_ADMINAPI_ENABLED
              value: "true"
            - name: REDPANDA_ADMINAPI_URLS
              value: "http://redpanda-svc.redpanda.svc.cluster.local:9644"
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-console-svc
  namespace: redpanda
spec:
  selector:
    app: redpanda-console
  ports:
    - name: http
      port: 8080
      targetPort: 8080
